// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuration Firebase [DefaultFirebaseOptions] pour l'app mobile WMA UA.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Cette app mobile ne cible pas le web. Utilisez le site PHP pour le web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Plateforme non supportée : ${defaultTargetPlatform.name}',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSttnS1qfZ-C41OVlIGKABBnlAobfGzk',
    appId: '1:421177402687:android:6e7850f4775d7ae7125f8a',
    messagingSenderId: '421177402687',
    projectId: 'uawma-70e70',
    storageBucket: 'uawma-70e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSNqcO6dXMrhNdBC4BBr6CxpoV8SP4lEY',
    appId: '1:421177402687:ios:cba0075b6037aba5125f8a',
    messagingSenderId: '421177402687',
    projectId: 'uawma-70e70',
    storageBucket: 'uawma-70e70.firebasestorage.app',
    androidClientId: '421177402687-146dphc13abqoqfrbve5ghhfk0pnrgr0.apps.googleusercontent.com',
    iosClientId: '421177402687-rejam18hsnu3pgu6a7nbp75hgns4gghk.apps.googleusercontent.com',
    iosBundleId: 'com.ua.wmahub',
  );

}