// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR4ddaz5ozSdh387Ai9xjelkBleSDeIMU',
    appId: '1:421177402687:web:4ca59fc8813e54fc125f8a',
    messagingSenderId: '421177402687',
    projectId: 'uawma-70e70',
    authDomain: 'uawma-70e70.firebaseapp.com',
    storageBucket: 'uawma-70e70.firebasestorage.app',
    measurementId: 'G-33E5GD1670',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSttnS1qfZ-C41OVlIGKABBnlAobfGzk',
    appId: '1:421177402687:android:6e7850f4775d7ae7125f8a',
    messagingSenderId: '421177402687',
    projectId: 'uawma-70e70',
    storageBucket: 'uawma-70e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSNqcO6dXMrhNdBC4BBr6CxpoV8SP4lEY',
    appId: '1:421177402687:ios:cba0075b6037aba5125f8a',
    messagingSenderId: '421177402687',
    projectId: 'uawma-70e70',
    storageBucket: 'uawma-70e70.firebasestorage.app',
    iosBundleId: 'com.ua.wmahub',
  );

}